<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="row mt-5">
    <h1> Nhập hàng hóa </h1>
    <input type="hidden" id="productList" value='<?= json_encode($this->productList ?? []) ?>'>
    <form method="post" action="/import-stock/do-add">
        <div class="container">
            <table class="table table-striped table-form mt-3">
                <thead>
                <tr>
                    <th style="width: 150px">Ngày</th>
                    <th>Tên hàng hóa</th>
                    <th style="width: 150px">Giá nhập</th>
                    <th style="width: 150px">Số lượng</th>
                    <th style="width: 400px">Ghi chú</th>
                    <th style="width: 100px">Thao tác</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <input class="form-control date-picker w-100" name="date[]" value="<?= date('d-m-Y') ?>" autocomplete="off" required/>
                    </td>
                    <td>
                        <select class="select-product form-control select2" name="productId[]" onchange="addInputRow(this)" required>
                            <option value="">Chọn hàng hóa</option>
                            <?php foreach ($this->productList as $id => $product): ?>
                            <option value="<?= $id ?>"><?= $product['name'] ?? '' ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td>
                        <div class="input-group">
                            <span class="input-group-text">VNĐ</span>
                            <input type="text" class="form-control" id="purchasePrice" name="purchasePrice[]" required>
                        </div>
                    </td>
                    <td>
                        <input class="form-control" type="number" name="quantity[]" value="1" required>
                    </td>
                    <td>
                        <textarea class="form-control" name="note[]" rows="1"></textarea>
                    </td>
                    <td>
                        <button class="btn btn-danger" onclick="removeInputRow(this)"> Xóa </button>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary float-end">Tạo</button>
            <a href="/import-stock" class="btn btn-danger float-end mx-2">Quay lại</a>
        </div>
    </form>
</div>

<script>
    let tableInputRowHtml = ``;
    let productList = [];
    $(document).ready(function() {
        tableInputRowHtml = $('.table-form').find('tbody').html();
        $('.select2').select2();
        initVariable();

        $('.date-picker').datepicker({
            format: 'dd-mm-yyyy',
            autoclose:true
        });
    });

    $(document).keypress(event => {
        if (event.which == '13') {
            event.preventDefault();
        }
    });

    function initVariable() {
        let data = $('#productList').val();
        productList = JSON.parse(data);
    }

    function addInputRow(elm) {
        let value = $(elm).val();
        const tbodyElm = $(elm).closest('tbody');
        const trElm = $(elm).closest('tr');

        const productData = productList[value] ?? {};
        const datePicked = trElm.find('.date-picker').val();

        trElm.find('#purchasePrice').val(productData.purchasePrice || 0);
        trElm.find('#sellingPrice').val(productData.sellingPrice || 0);

        if (value) {
            if ($('.select-product').last().val() !== '') {
                tbodyElm.append(tableInputRowHtml);
                tbodyElm.find('.select2').select2();
                const datePicker = tbodyElm.find('.date-picker');
                datePicker.val();
                datePicker.datepicker({
                    format: 'dd-mm-yyyy',
                    autoclose:true
                });
                datePicker.val(datePicked);
            }
        }
    }

    function removeInputRow(elm) {
        $(elm).closest('tr').remove();
    }
</script>