<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="row mt-5">
    <h1> Chỉnh sửa nhập hàng ngày <?= $this->date ?></h1>
    <input type="hidden" id="productList" value='<?= json_encode($this->productList ?? []) ?>'>
    <form method="post" action="/import-stock/do-edit">
        <div class="container">
            <table class="table table-striped table-form mt-3">
                <thead>
                <tr>
                    <th style="width: 150px">Ngày</th>
                    <th style="min-width: 250px">Tên hàng hóa</th>
                    <th style="width: 150px">Giá nhập</th>
                    <th style="width: 80px">Số lượng</th>
                    <th style="width: 400px">Ghi chú</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($this->importStockList as $importStockId => $importStockData):
                    $date = $importStockData['date'] ?? '';
                    $quantity = $importStockData['quantity'] ?? 0;
                    $purchasePrice = $importStockData['purchasePrice'] ?? 0;
                    $note = $importStockData['note'] ?? '';
                ?>
                <tr>
                    <div>
                        <input type="hidden" name="importStockId[]" value="<?= $importStockId ?>">
                    </div>
                    <td>
                        <input class="form-control date-picker w-100" name="date[]" value="<?= $date ?>" autocomplete="off" required/>
                    </td>
                    <td>
                        <select class="select-product form-control select2" name="productId[]" required>
                            <option value="">Chọn hàng hóa</option>
                            <?php
                            foreach ($this->productList as $productId => $productData):
                                $isSelected = !empty($importStockData['productId']) && $importStockData['productId'] == $productId;
                                $selected = $isSelected ? 'selected' : '';
                                $productName = $productData['name'] ?? '-';
                            ?>
                                <option value="<?= $productId ?>" <?= $selected ?> > <?= $productName ?> </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td>
                        <div class="input-group">
                            <span class="input-group-text">VNĐ</span>
                            <input type="text" class="form-control" id="purchasePrice" value="<?= $purchasePrice ?>" name="purchasePrice[]" required>
                        </div>
                    </td>
                    <td>
                        <input class="form-control" type="number" name="quantity[]" value="<?= $quantity ?>" value="1" required>
                    </td>
                    <td>
                        <textarea class="form-control" name="note[]" rows="1"><?= $note ?></textarea>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary float-end">Lưu</button>
            <a href="/import-stock" class="btn btn-danger float-end mx-2">Quay lại</a>
        </div>
    </form>
</div>

<script>
    let tableInputRowHtml = ``;
    let productList = [];
    $(document).ready(function() {
        tableInputRowHtml = $('.table-form').find('tbody').html();
    });

    $(document).keypress(event => {
        if (event.which == '13') {
            event.preventDefault();
        }
    });
</script>