<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container mt-5">
    <h1 class="mb-5"> Nhập hàng </h1>
    <div class="my-2">
        <div class="d-flex">
            <a href="/import-stock/add" class="btn btn-primary"> Thêm mới +</a>
            <div class="input-group w-50 ms-3">
                <button class="btn btn-primary" onclick="editByDate()"> Chỉnh sửa </button>
                <input class="form-control date-picker" id="editDate" name="date" autocomplete="off" placeholder="Nhập ngày chỉnh sửa..." required/>
            </div>
        </div>
    </div>
    <table id="dataTable" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>STT</th>
            <th>Ngày</th>
            <th>Tên hàng hóa</th>
            <th>Giá nhập</th>
            <th>Số lượng</th>
            <th>Thành tiền</th>
            <th>Ghi chú</th>
            <th>Thao tác</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $no = 1;
        foreach ($this->importStockList as $id => $row):
            if (empty($row['productId'])) {
                continue;
            }
            $productId = $row['productId'];
            $productName = $this->productList[$productId]['name'] ?? '-';
            $date = !empty($row['date']) ? $row['date'] : '-';
            $purchasePrice = !empty($row['purchasePrice']) ? $row['purchasePrice'] : 0;
            $quantity = !empty($row['quantity']) ? $row['quantity'] : 1;
            $note = $row['note'] ?? '-';
        ?>
        <tr id="row-<?= $id ?>">
            <td><?= $no ?></td>
            <td><?= $this->escapeHtml($date) ?></td>
            <td><?= $this->escapeHtml($productName) ?></td>
            <td><?= $this->escapeHtml(number_format($purchasePrice)) ?> VNĐ</td>
            <td><?= $this->escapeHtml(number_format($quantity)) ?></td>
            <td><?= $this->escapeHtml(number_format($purchasePrice*$quantity)) ?> VNĐ</td>
            <td><?= $this->escapeHtml($note) ?></td>
            <td>
                <button class="btn btn-danger" onclick='remove("<?= $id ?>")'> Xóa </button>
            </td>
        </tr>
        <?php $no++; endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    const tabeId = '#dataTable';
    const table = new DataTable(tabeId, {
        order: [[1, 'desc']],
        columnDefs: [
            {
                searchable: false,
                orderable: false,
                targets: [0, -1]
            }
        ]
    });
    table.on('order.dt search.dt', function () {
        let i = 1;
        table.cells(null, 0, {search: 'applied', order: 'applied'}).every(function (cell) {
            this.data(i++);
        });
    }).draw();

    $(document).ready(function() {
        $('.date-picker').datepicker({
            format: 'dd-mm-yyyy',
            autoclose:true
        });
    });

    function remove(id) {
        if (!confirm('Bạn có chắc chắn muốn xóa?')) {
            return;
        }
        $.ajax({
            url: '/import-stock/do-delete',
            type: 'DELETE',
            contentType: 'application/json',
            data: JSON.stringify({ id: id }),
            success: function (response) {
                debugger
                if (response.success) {
                    table.row(`#row-${id}`).remove().draw(false);
                } else {
                    alert(`Đã xảy ra lỗi khi xóa. ${response.message || 'error unknown'}`);
                }
            },
            error: function (xhr, status, error) {
                console.error('Lỗi:', error);
                alert('Đã xảy ra lỗi khi xóa.');
            },
        });
    }

    function editByDate() {
        const date = $('#editDate').val();
        if (!date) {
            alert("Hãy nhập ngày chỉnh sửa !");
            return;
        }
        location.href = `/import-stock/edit/${date}`;
    }
</script>