version: "3.9"

services:
  app:
    build:
      context: ./docker
      dockerfile: php/Dockerfile
    container_name: sam-pet-${APP_ENV:-dev}
    volumes:
      - .:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8080:80"
    env_file:
      - .env
