<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container mt-4">
    <h1 class="mb-3"> Sổ doanh thu</h1>

    <div class="my-2">
        <div class="d-flex">
            <div class="input-group w-auto">
                <input class="form-control date-picker" id="date" name="date" autocomplete="off" placeholder="Chọn ngày..." style="width:140px"/>
                <button class="btn btn-primary" onclick="addByDate()">+ Thêm mới</button>
            </div>
        </div>
    </div>
    <table id="dataTable" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>STT</th>
            <th>Ngày</th>
            <th>Tổng cộng</th>
            <th>Thao tác</th>
        </tr>
        </thead>
    </table>
</div>
<script>
    const table = initDataTable('#dataTable', {
        ...DATA_TABLES_CONFIG,
        ajax: {
            url: 'export-invoice/data-table-server-side',
            type: 'POST'
        },
        columns: [
            { name: 'no', data: 'no' },
            { name: 'date', data: 'date' },
            { name: 'total', data: 'total', render: $.fn.dataTable.render.number( ',') },
            {
                name: 'action', data: 'id',
                render: (id) =>
                    `<button class="btn btn-secondary btn-sm" onclick="reviewPdf('${id}')">Xem PDF</button>` +
                    `<a class="btn btn-primary btn-sm ms-1" href="/export-invoice/edit/${id}">Sửa</a>` +
                    `<button class="btn btn-danger btn-sm ms-1" onclick="removeRow('export-invoice','${id}',table)">Xóa</button>`
            }
        ],
        serverSide: true
    });

    function remove(id) { removeRow('export-invoice', id, table); }

    function reviewPdf(id) {
        if (!id) {
            alert("ID null !");
            return;
        }
        window.open(`/export-invoice/pdf/${id}`, "_blank");
    }

    function addByDate() {
        const date = $('#date').val();
        if (!date) {
            alert("Hãy nhập ngày thêm mới !");
            return;
        }
        location.href = `/export-invoice/add/${date}`;
    }
</script>