5<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container mt-5">
    <h1 class="mb-5"> Danh sách hóa đơn </h1>
    <div class="my-2">
        <div class="d-flex">
            <div class="input-group w-50 ms-3">
                <input class="form-control date-picker" id="date" name="date" autocomplete="off" placeholder="Nhập ngày..." required/>
                <button class="btn btn-primary" onclick="addByDate()"> Thêm mới </button>
                <button class="btn btn-success" onclick="editByDate()"> Chỉnh sửa </button>
            </div>
        </div>
    </div>
    <table id="dataTable" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>STT</th>
            <th>Ngày</th>
            <th>Tổng cộng</th>
            <th>Thao tác</th>
        </tr>
        </thead>
    </table>
</div>
<script>
    const table = initDataTable('#dataTable', {
        ...DATA_TABLES_CONFIG,
        ajax: {
            url: 'export-invoice/data-table-server-side',
            type: 'POST'
        },
        columns: [
            { name: 'no', data: 'no' },
            { name: 'date', data: 'date' },
            { name: 'total', data: 'total', render: $.fn.dataTable.render.number( ',') },
            { name: 'action', data: 'action' }
        ],
        serverSide: true
    });

    function remove(id) {
        if (!confirm('Bạn có chắc chắn muốn xóa?')) {
            return;
        }
        $.ajax({
            url: '/export-invoice/do-delete',
            type: 'DELETE',
            contentType: 'application/json',
            data: JSON.stringify({ id: id }),
            success: function (response) {
                if (response.success) {
                    table.draw(false);
                    addFlashMessage(`Xoá thành công`);
                } else {
                    addFlashMessage(`Đã xảy ra lỗi khi xóa. ${response.message || 'error unknown'}`, FLASH_MESSAGE_TYPE_ERROR);
                }
            },
            error: function (xhr, status, error) {
                addFlashMessage('Đã xảy ra lỗi khi xóa: ' + error, FLASH_MESSAGE_TYPE_ERROR);
            }
        });
    }

    function reviewPdf(id) {
        if (!id) {
            alert("ID null !");
            return;
        }
        window.open(`/export-invoice/pdf/${id}`, "_blank");
    }

    function addByDate() {
        const date = $('#date').val();
        if (!date) {
            alert("Hãy nhập ngày thêm mới !");
            return;
        }
        location.href = `/export-invoice/add/${date}`;
    }

    function editByDate() {
        const date = $('#date').val();
        if (!date) {
            alert("Hãy nhập ngày chỉnh sửa !");
            return;
        }
        location.href = `/export-invoice/edit/${date}`;
    }
</script>