<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<style>
    .btn-outline-primary:has(input[type="radio"]:checked) {
        background: #0d6efd;
        color: white;
    }

    .btn-outline-danger:has(input[type="radio"]:checked) {
        background: #dc3545;
        color: white
    }
</style>
<div class="container mt-5">
<div class="container mt-5">
    <h1 class="mb-3"> Cập nhật trạng thái hóa đơn</h1>

    <div class="my-2">
        <a href="/product" class="btn btn-sm btn-outline-secondary">← Quay lại kho</a>
    </div>
    <form method="post" action="/product/do-add-invoice-check">
        <table id="dataTable" class="table table-striped table-headers-sticky table-footers-sticky" style="width:100%">
            <thead>
            <tr style="position:sticky;background: white">
                <th>STT</th>
                <th>Tên</th>
                <th>Giá nhập</th>
                <th>Giá bán</th>
                <th>Hoá đơn</th>
            </tr>
            </thead>
            <tbody>
            <?php
            $invoiceCheckTrue = \Application\Model\Product::INVOICE_CHECK_TRUE;
            $invoiceCheckFalse = \Application\Model\Product::INVOICE_CHECK_FALSE;
            $i = 1;
            foreach ($this->productList as $product):
                $id = $product['id'] ?? '';
                $invoiceCheck = $product['invoiceCheck'] ?? $invoiceCheckFalse;
                $isInvoiceCheckTrue = $invoiceCheck === $invoiceCheckTrue;
                $isInvoiceCheckFalse = $invoiceCheck === $invoiceCheckFalse;
            ?>
                <tr>
                    <td><?= $i ?></td>
                    <td><?= $product['name'] ?? "NO NAME" ?></td>
                    <td><?= $product['purchasePrice'] ? $product['purchasePrice']/1000 : "0" ?>K</td>
                    <td><?= $product['sellingPrice'] ? $product['sellingPrice']/1000 : "0" ?>K</td>
                    <td>
                        <label class="btn btn-outline-primary" for="invoiceCheckTrue<?= $id ?>">
                            <span> Có </span>
                            <input id="invoiceCheckTrue<?= $id ?>" type="radio" name="invoiceCheckList[<?= $id ?>]" value="<?= $invoiceCheckTrue ?>" <?= $isInvoiceCheckTrue ? 'checked' : '' ?>>
                        </label>
                        <label class="btn btn-outline-danger ms-5" for="invoiceCheckFalse<?= $id ?>">
                            <span> Không </span>
                            <input id="invoiceCheckFalse<?= $id ?>" type="radio" name="invoiceCheckList[<?= $id ?>]" value="<?= $invoiceCheckFalse ?>" <?= $isInvoiceCheckFalse ? 'checked' : '' ?>>
                        </label>
                    </td>
                </tr>
                <?php
                $i++;
            endforeach; ?>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="8" style="z-index: 999">
                    <button class="form-control bg-primary text-white" type="submit" >Cập nhật</button>
                </td>
            </tr>
            </tfoot>
        </table>
    </form>
</div>