<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="row mt-5">
    <h1> Thêm sản phẩm </h1>
    <form method="post" action="/product/do-add">
        <div class="mb-3">
            <label class="form-label">Tên</label>
            <input type="text" class="form-control" id="name" name="name" required>
        </div>
        <div class="mb-3">
            <label class="form-label">Đơn vị</label>
            <input type="text" class="form-control" id="name" value="Cái" name="unit" required>
        </div>
        <div class="mb-3">
            <label class="form-label">Giá nhập</label>
            <div class="input-group">
                <span class="input-group-text">VNĐ</span>
                <input type="text" class="form-control" name="purchasePrice" required>
            </div>
        </div>
        <div class="mb-3">
            <label class="form-label">Giá bán</label>
            <div class="input-group">
                <span class="input-group-text">VNĐ</span>
                <input type="text" class="form-control" name="sellingPrice" required>
            </div>
        </div>
        <div class="mb-3">
            <label class="form-label">Tồn đầu kì</label>
            <input type="number" class="form-control" name="initStock" required value="0">
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary float-end">Tạo</button>
            <a href="/product" class="btn btn-danger float-end mx-2">Quay lại</a>
        </div>
    </form>
</div>