<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container mt-5">
    <h1 class="mb-5"> Quản lý kho</h1>
    <div class="my-2">
        <a href="/product/add" class="btn btn-primary">+ Thêm mới</a>
    </div>
    <table id="dataTable" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>STT</th>
            <th>Tên</th>
            <th>Đơn vị</th>
            <th>Giá nhập</th>
            <th>Giá bán</th>
            <th>Lãi</th>
            <th>Tồn đầu kỳ</th>
            <th>Nhập</th>
            <th>Xuất</th>
            <th>Còn lại</th>
            <th>Thao tác</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $no = 1;
        foreach ($this->productList as $id => $row):
            $name = $row['name'] ?? '-';
            $unit = $row['unit'] ?? '-';
            $sellingPrice = !empty($row['sellingPrice']) ? $row['sellingPrice'] : 0;
            $purchasePrice = !empty($row['purchasePrice']) ? $row['purchasePrice'] : 0;
            $initStock = !empty($row['initStock']) ? $row['initStock'] : 0;
            $importStock = !empty($row['importStock']) ? $row['importStock'] : 0;
            $exportStock = !empty($row['exportStock']) ? $row['exportStock'] : 0;
            $remainStock = $initStock + $importStock - $exportStock;
        ?>
        <tr id="row-<?= $id ?>">
            <td><?= $no ?></td>
            <td><?= $this->escapeHtml($name) ?></td>
            <td><?= $this->escapeHtml($unit) ?></td>
            <td><?= $this->escapeHtml(number_format($sellingPrice)) ?> VNĐ</td>
            <td><?= $this->escapeHtml(number_format($purchasePrice)) ?> VNĐ</td>
            <td><?= $this->escapeHtml(number_format($purchasePrice - $sellingPrice)) ?> VNĐ</td>
            <td><?= $this->escapeHtml(number_format($initStock)) ?></td>
            <td><?= $this->escapeHtml(number_format($importStock)) ?></td>
            <td><?= $this->escapeHtml(number_format($exportStock)) ?></td>
            <td><?= $this->escapeHtml(number_format($remainStock)) ?></td>
            <td>
                <a href="/product/edit/<?= $id ?>" class="btn btn-primary">Chỉnh sửa</a>
                <button class="btn btn-danger" onclick='remove("<?= $id ?>")'> Xóa </button>
            </td>
        </tr>
        <?php $no++; endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    const tabeId = '#dataTable';
    const table = new DataTable(tabeId, {
        order: [[1, 'desc']],
        columnDefs: [
            {
                searchable: false,
                orderable: false,
                targets: [0, -1]
            }
        ]
    });
    table.on('order.dt search.dt', function () {
        let i = 1;
        table.cells(null, 0, {search: 'applied', order: 'applied'}).every(function (cell) {
            this.data(i++);
        });
    }).draw();

    $(document).ready(function() {
    });

    function remove(id) {
        if (!confirm('Bạn có chắc chắn muốn xóa?')) {
            return;
        }
        $.ajax({
            url: '/product/do-delete',
            type: 'DELETE',
            contentType: 'application/json',
            data: JSON.stringify({ id: id }),
            success: function (response) {
                if (response.success) {
                    table.row(`#row-${id}`).remove().draw(false);
                } else {
                    alert(`Đã xảy ra lỗi khi xóa. ${response.message || 'error unknown'}`);
                }
            },
            error: function (xhr, status, error) {
                console.error('Lỗi:', error);
                alert('Đã xảy ra lỗi khi xóa.');
            },
        });
    }
</script>