<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container mt-5">
    <h1 class="mb-5"> Quản lý kho</h1>
    <div class="my-2">
        <a href="/product/add" class="btn btn-primary">+ Thêm mới</a>
    </div>
    <table id="dataTable" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>STT</th>
            <th>Tên</th>
            <th>Đơn vị</th>
            <th>Giá nhập</th>
            <th>Giá bán</th>
            <th>Lãi</th>
            <th>Tồn đầu kỳ</th>
            <th>Nhập</th>
            <th>Xuất</th>
            <th>Còn lại</th>
            <th>Thao tác</th>
        </tr>
        </thead>
    </table>
</div>
<script>
    const table = initDataTable('#dataTable', {
        ...DATA_TABLES_CONFIG,
        ajax: {
            url: 'product/data-table-server-side',
            type: 'POST'
        },
        columns: [
            { name: 'no', data: 'no' },
            { name: 'productName', data: 'name' },
            { name: 'unit', data: 'unit' },
            { name: 'purchasePrice', data: 'purchasePrice', render: $.fn.dataTable.render.number( ',') },
            { name: 'sellingPrice', data: 'sellingPrice', render: $.fn.dataTable.render.number( ',') },
            { name: 'profit', data: 'profit', render: $.fn.dataTable.render.number( ',') },
            { name: 'initStock', data: 'initStock' },
            { name: 'importStock', data: 'importStock' },
            { name: 'exportStock', data: 'exportStock' },
            { name: 'remainStock', data: 'remainStock' },
            { name: 'action', data: 'action' }
        ],
        processing: true,
        serverSide: true
    });

    function remove(id) {
        if (!confirm('Bạn có chắc chắn muốn xóa?')) {
            return;
        }
        $.ajax({
            url: '/product/do-delete',
            type: 'DELETE',
            contentType: 'application/json',
            data: JSON.stringify({ id: id }),
            success: function (response) {
                if (response.success) {
                    table.draw(false);
                } else {
                    alert(`Đã xảy ra lỗi khi xóa. ${response.message || 'error unknown'}`);
                }
            },
            error: function (xhr, status, error) {
                console.error('Lỗi:', error);
                alert('Đã xảy ra lỗi khi xóa.');
            },
        });
    }
</script>