<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container mt-5">
    <h1 class="mb-5"> Điều trị - Spa </h1>
    <div class="my-2">
        <div class="d-flex">
            <a href="/vet-care/add" class="btn btn-primary"> Thêm mới +</a>
        </div>
    </div>
    <table id="dataTable" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>STT</th>
            <th>Ngày</th>
            <th>Tiền điều trị</th>
            <th>Tiền spa</th>
            <th>Ghi chú</th>
            <th>Thao tác</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $no = 1;
        foreach ($this->vetCareList as $id => $row):
            $date = !empty($row['date']) ? $row['date'] : '-';
            $treatmentAmount = !empty($row['treatmentAmount']) ? $row['treatmentAmount'] : 0;
            $spaAmount = !empty($row['spaAmount']) ? $row['spaAmount'] : 0;
            $note = $row['note'] ?? '-';
        ?>
        <tr id="row-<?= $id ?>">
            <td><?= $no ?></td>
            <td><?= $this->escapeHtml($date) ?></td>
            <td><?= $this->escapeHtml(number_format($treatmentAmount)) ?> VNĐ</td>
            <td><?= $this->escapeHtml(number_format($spaAmount)) ?> VNĐ</td>
            <td><?= $this->escapeHtml($note) ?></td>
            <td>
                <a href="/vet-care/edit/<?= $id ?>" class="btn btn-primary">Chỉnh sửa</a>
                <button class="btn btn-danger" onclick='remove("<?= $id ?>")'> Xóa </button>
            </td>
        </tr>
        <?php $no++; endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    const table = initDataTable();

    function remove(id) {
        if (!confirm('Bạn có chắc chắn muốn xóa?')) {
            return;
        }
        $.ajax({
            url: '/vet-care/do-delete',
            type: 'DELETE',
            contentType: 'application/json',
            data: JSON.stringify({ id: id }),
            success: function (response) {
                if (response.success) {
                    table.row(`#row-${id}`).remove().draw(false);
                } else {
                    alert(`Đã xảy ra lỗi khi xóa. ${response.message || 'error unknown'}`);
                }
            },
            error: function (xhr, status, error) {
                console.error('Lỗi:', error);
                alert('Đã xảy ra lỗi khi xóa.');
            },
        });
    }
</script>