<?php
$this->headScript()->appendFile('https://code.highcharts.com/highcharts.js')
?>
<div class="container">
    <div class="mt-3">
        <a class="btn btn-primary" href="/"> Biểu đồ doanh thu </a>
        <a class="btn btn-primary" href="/overview/expenses"> Biểu đồ Thu/Chi </a>
    </div>

    <div id="dailyChart" class="chart"></div>
    <div id="monthlyChart" class="chart"></div>
</div>
<script>
    const data = JSON.parse(`<?= json_encode($this->data) ?>`);

    $(function() {
        renderChart('dailyChart');
        renderChart('monthlyChart', true);
    })

    function aggregateByMonth(data) {
        const result = {};

        data.forEach(item => {
            const date = new Date(item[0]);
            const monthKey = `${date.getUTCFullYear()}-${date.getUTCMonth()}`;

            if (!result[monthKey]) {
                result[monthKey] = 0;
            }
            result[monthKey] += item[1];
        });

        return Object.keys(result).map(key => {
            const [year, month] = key.split('-').map(Number);
            return [Date.UTC(year, month, 1), result[key]];
        });
    }

    function aggregateByQuarter(data) {
        const result = {};

        data.forEach(item => {
            const date = new Date(item[0]);
            const quarterInYear = Math.floor(date.getUTCMonth() / 3) + 1;
            const quarterKey = `${date.getUTCFullYear()}-${quarterInYear}`;

            if (!result[quarterKey]) {
                result[quarterKey] = 0;
            }
            result[quarterKey] += item[1];
        });

        return Object.keys(result).map(key => {
            const [year, quarterInYear] = key.split('-').map(Number);
            return [Date.UTC(year, quarterInYear * 3, 1), result[key]];
        });
    }

    function renderChart(id, isMonthly = false) {
        const dateFormat = isMonthly ? '%m-%Y' : '%d-%m-%Y';
        let option = {
            title: {
                text: 'Thống kê thu/chi' + (isMonthly ? ' (tháng)' : ' (quý)')
            },
            xAxis: {
                type: 'datetime',
                title: {
                    text: 'Thời gian'
                },
                labels: {
                    format: `{value:${dateFormat}}`
                }
            },
            yAxis: {
                title: {
                    text: 'VNĐ'
                }
            },
            tooltip: {
                xDateFormat: `${dateFormat}`,
                shared: true
            },
            series: [
                {
                    name: 'Doanh thu',
                    data: isMonthly ? aggregateByMonth(data.revenue) : aggregateByQuarter(data.revenue)
                },
                {
                    name: 'Chi',
                    data: isMonthly ? aggregateByMonth(data.expenses) : aggregateByQuarter(data.expenses)
                },
                {
                    name: 'Chi - Rút tiết kiệm',
                    data: isMonthly ? aggregateByMonth(data.savings) : aggregateByQuarter(data.savings)
                },
                {
                    name: 'Còn lại',
                    data: isMonthly ? aggregateByMonth(data.remaining) : aggregateByQuarter(data.remaining)
                },
            ]
        }
        Highcharts.chart(id, option);
    }

    function showChart(id) {

    }

</script>
