<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container mt-5">
    <h1 class="mb-5"> Báo cáo thu - chi </h1>
    <div class="container row" style="font-size: 10px">
        <div class="alert alert-info p-2 col-2 float-start">Tổng tiền tồn:
            <span class="fw-bold"></span>
        </div>
        <div class="alert alert-info p-2 col-2 float-start ms-2">Tổng thu:
            <span class="fw-bold" id="totalRevenue"></span>
        </div>
        <div class="alert alert-info p-2 col-2 float-start ms-2">Tổng chi:
            <span class="fw-bold" id="totalExpenses"></span>
        </div>
        <div class="alert alert-info p-2 col-2 float-start ms-2">Tiền dư/thiếu:
            <span class="fw-bold" id="totalMissingAmount"></span>
        </div>
        <div class="alert alert-info p-2 col-2 float-start ms-2">Tiền còn lại:
            <span class="fw-bold" id="totalProfit"></span>
        </div>
    </div>
    <div class="my-2">
        <div class="d-flex">
            <a href="/report/add" class="btn btn-primary"> Thêm mới +</a>
        </div>
    </div>
    <table id="dataTable" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>STT</th>
            <th>Ngày</th>
            <th>Thu pet shop</th>
            <th>Lãi pet shop</th>
            <th>Thu spa</th>
            <th>Thu điều trị</th>
            <th>Lãi điều trị</th>
            <th>Tổng thu</th>
            <th>Tổng chi</th>
            <th>Còn lại</th>
            <th>Tiền dư/thiếu</th>
            <th>Ghi chú</th>
            <th>Thao tác</th>
        </tr>
        </thead>
    </table>
</div>
<script>
    const table = initDataTable('#dataTable', {
        ...DATA_TABLES_CONFIG,
        ajax: {
            url: 'report/data-table-server-side',
            type: 'POST',
            dataSrc: function (json) {
                reloadReportHeaderInfo(json);
                return json.data || {};
            }
        },
        columns: [
            { name: 'no', data: 'no' },
            { name: 'date', data: 'date' },
            { name: 'petShopRevenue', data: 'petShopRevenue', render: $.fn.dataTable.render.number( ',') },
            { name: 'petShopProfit', data: 'petShopProfit', render: $.fn.dataTable.render.number( ',') },
            { name: 'spaRevenue', data: 'spaRevenue', render: $.fn.dataTable.render.number( ',') },
            { name: 'treatmentRevenue', data: 'treatmentRevenue', render: $.fn.dataTable.render.number( ',') },
            { name: 'treatmentProfit', data: 'treatmentProfit', render: $.fn.dataTable.render.number( ',') },
            { name: 'revenue', data: 'revenue', render: $.fn.dataTable.render.number( ',') },
            { name: 'expenses', data: 'expenses', render: $.fn.dataTable.render.number( ',') },
            { name: 'remaining', data: 'remaining', render: $.fn.dataTable.render.number( ',') },
            { name: 'missingAmount', data: 'missingAmount', render: $.fn.dataTable.render.number( ',') },
            { name: 'note', data: 'note' },
            { name: 'action', data: 'action' }
        ],
        serverSide: true
    });

    function remove(id) {
        if (!confirm('Bạn có chắc chắn muốn xóa?')) {
            return;
        }
        $.ajax({
            url: '/report/do-delete',
            type: 'DELETE',
            contentType: 'application/json',
            data: JSON.stringify({ id: id }),
            success: function (response) {
                if (response.success) {
                    table.draw(false);
                } else {
                    alert(`Đã xảy ra lỗi khi xóa. ${response.message || 'error unknown'}`);
                }
            },
            error: function (xhr, status, error) {
                console.error('Lỗi:', error);
                alert('Đã xảy ra lỗi khi xóa.');
            },
        });
    }

    function reloadReportHeaderInfo(json) {
        const totalRevenue = json.totalRevenue || 0;
        const totalExpenses = json.totalExpenses || 0;
        const totalMissingAmount = json.totalMissingAmount || 0;
        const totalProfit = totalRevenue - totalExpenses + totalMissingAmount;

        $('#totalRevenue').html(formatNumber(totalRevenue) + ' VNĐ')
        $('#totalExpenses').html(formatNumber(totalExpenses) + ' VNĐ')
        $('#totalMissingAmount').html(formatNumber(totalMissingAmount) + ' VNĐ')
        $('#totalProfit').html(formatNumber(totalProfit) + ' VNĐ')
    }
</script>