<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php
$successMessages = $this->flashMessenger()->getSuccessMessages();
$errorMessages = $this->flashMessenger()->getErrorMessages();
$infoMessages = $this->flashMessenger()->getMessages();
?>

<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Laminas MVC Skeleton')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?= $this->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            ])
            ->appendStylesheet($this->basePath('css/style.css'))
            ->appendStylesheet($this->basePath('css/bootstrap.min.css'))

            ->appendStylesheet('https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css')
            ->appendStylesheet('https://cdn.datatables.net/select/2.1.0/css/select.dataTables.min.css')

            ->appendStylesheet('https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css')
            ->appendStylesheet('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/css/bootstrap-datepicker.min.css')
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->appendFile($this->basePath('js/bootstrap.min.js'))
            ->appendFile('https://code.jquery.com/jquery-3.7.1.min.js')

            ->appendFile('https://cdn.datatables.net/2.1.8/js/dataTables.min.js')
            ->appendFile('https://cdn.datatables.net/plug-ins/2.1.8/sorting/date-eu.js')
            ->appendFile('https://cdn.datatables.net/select/2.1.0/js/dataTables.select.min.js')
            ->appendFile('https://cdn.datatables.net/select/2.1.0/js/select.dataTables.min.js')
            ->appendFile('https://cdn.datatables.net/select/2.1.0/js/select.dataTables.min.js')
            ->appendFile($this->basePath('js/custom.dataTables.js'))

            ->appendFile('https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js')
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/js/bootstrap-datepicker.min.js')

            ->appendFile($this->basePath('js/common.js'))
        ?>
    </head>
    <body>
        <div class="flash-messages">
            <?php if (!empty($successMessages)): ?>
                <?php foreach ($successMessages as $message): ?>
                    <div class="alert alert-success m-0 p-1">
                        <?= $this->escapeHtml($message); ?>
                        <button type="button" class="btn-close float-end" onclick="closeAlertMessage(this)"></button>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php if (!empty($errorMessages)): ?>
                <?php foreach ($errorMessages as $message): ?>
                    <div class="alert alert-danger m-0 p-1">
                        <?= $this->escapeHtml($message); ?>
                        <button type="button" class="btn-close float-end" onclick="closeAlertMessage(this)"></button>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php if (!empty($infoMessages)): ?>
                <?php foreach ($infoMessages as $message): ?>
                    <div class="alert alert-info m-0 p-1">
                        <?= $this->escapeHtml($message); ?>
                        <button type="button" class="btn-close float-end" onclick="closeAlertMessage(this)"></button>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>

        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/product">Sam Pet - Dịch Vụ Thú Cưng</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="/product">Quản lý kho</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/import-stock">Nhập hàng</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/export-stock">Xuất hàng</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/vet-care">Điều trị - Spa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/expenses">Quản lý chi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/report">Báo cáo thu - chi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy;2024 Sampet Project
                </p>
            </footer>
        </div>
        <div class="overlay-loading">
            <div class="spinner-border text-info"></div>
        </div>

        <div class="calculate-container">
            <button class="btn btn-warning opacity-50" type="button" data-bs-toggle="collapse" data-bs-target="#calculate" aria-expanded="false" aria-controls="calculate">
                Máy tính
            </button>
            <div class="collapse" id="calculate">
                <div class="card card-body w-100">
                    <input type="text" id="calculateExpression" oninput="loadResultCalculate()" placeholder="Nhập phép tính...">
                    <div>
                        = <span id="calculateResult"></span>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
