<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="row mt-5">
    <h1> Chỉnh sửa sản phẩm </h1>
    <form method="post" action="/product/do-edit">
        <div class="mb-3">
            <label class="form-label">Tên</label>
            <input type="text" class="form-control" id="name" name="name" value="<?= $this->data['name'] ?>">
        </div>
        <div class="mb-3">
            <label class="form-label">Đơn vị</label>
            <input type="text" class="form-control" id="name"name="unit" value="<?= $this->data['unit'] ?>">
        </div>
        <div class="mb-3">
            <label class="form-label">Giá nhập</label>
            <div class="input-group">
                <span class="input-group-text">VNĐ</span>
                <input type="text" class="form-control" name="sellingPrice" value="<?= $this->data['sellingPrice'] ?>">
            </div>
        </div>
        <div class="mb-3">
            <label class="form-label">Giá bán</label>
            <div class="input-group">
                <span class="input-group-text">VNĐ</span>
                <input type="text" class="form-control" name="purchasePrice" value="<?= $this->data['purchasePrice'] ?>">
            </div>
        </div>
        <div>
            <input type="hidden" name="id" value="<?= $this->data['id'] ?>">
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary float-end">Lưu</button>
            <a href="/product" class="btn btn-danger float-end mx-2">Quay lại</a>
        </div>
    </form>
</div>