<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container mt-5">
    <h1 class="mb-5"> Xuất hàng </h1>
    <div class="my-2">
        <a href="/export-stock/add" class="btn btn-primary">+ Thêm mới</a>
    </div>
    <table id="productTable" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>STT</th>
            <th>Tên</th>
            <th>Đơn vị</th>
            <th>Giá nhập</th>
            <th>Giá bán</th>
            <th>Lãi</th>
            <th>Thao tác</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $no = 1;
        foreach ($this->data as $id => $row): ?>
        <tr id="row-<?= $id ?>">
            <td><?= $no ?></td>
            <td><?= $this->escapeHtml($row['name']) ?></td>
            <td><?= $this->escapeHtml($row['unit']) ?></td>
            <td><?= $this->escapeHtml(number_format($row['sellingPrice'])) ?> VNĐ</td>
            <td><?= $this->escapeHtml(number_format($row['purchasePrice'])) ?> VNĐ</td>
            <td><?= $this->escapeHtml(number_format($row['purchasePrice']- $row['sellingPrice'])) ?> VNĐ</td>
            <td>
                <a href="/product/edit/<?= $id ?>" class="btn btn-primary">Chỉnh sửa</a>
                <a href='javascript:remove("<?= $id ?>")' class="btn btn-danger">Xóa</a>
            </td>
        </tr>
        <?php $no++; endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    const tabeId = '#productTable';
    const table = new DataTable(tabeId);

    $(document).ready(function() {
    });

    function remove(id) {
        if (!confirm('Bạn có chắc chắn muốn xóa?')) {
            return;
        }
        $.ajax({
            url: '/product/do-delete',
            type: 'DELETE',
            contentType: 'application/json',
            data: JSON.stringify({ id: id }),
            success: function (response) {
                if (response.success) {
                    table.row(`#row-${id}`).remove().draw(false);
                } else {
                    alert(`Đã xảy ra lỗi khi xóa. ${response.message || 'error unknown'}`);
                }
            },
            error: function (xhr, status, error) {
                console.error('Lỗi:', error);
                alert('Đã xảy ra lỗi khi xóa.');
            },
        });
    }
</script>