<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col mt-5">
        <a class="btn btn-primary" href="https://getlaminas.org/" target="_blank">Laminas Project Portal &raquo;</a>
    </div>
    <div class="col mt-5">
        <a class="btn btn-primary" href="https://getlaminas.org/" target="_blank">Laminas Project Portal &raquo;</a>
    </div>
    <div class="col mt-5">
        <a class="btn btn-primary" href="https://getlaminas.org/" target="_blank">Laminas Project Portal &raquo;</a>
    </div>
    <div class="col mt-5">
        <a class="btn btn-primary" href="https://getlaminas.org/" target="_blank">Laminas Project Portal &raquo;</a>
    </div>
</div>
