<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="row mt-5">
    <h1> Nhập chi </h1>
    <form method="post" action="/expenses/do-add">
        <div class="container">
            <table class="table table-striped table-form mt-3">
                <thead>
                <tr>
                    <th style="width: 150px">Ngày</th>
                    <th>Lý do chi</th>
                    <th style="width: 150px">Số tiền</th>
                    <th style="width: 150px">Người chi</th>
                    <th style="width: 400px">Ghi chú</th>
                    <th style="width: 100px">Thao tác</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <input class="form-control date-picker w-100" name="date[]" value="<?= date('d-m-Y') ?>" autocomplete="off" required/>
                    </td>
                    <td>
                        <input type="text" class="form-control reason" id="reason" name="reason[]" required onchange="addInputRow(this)">
                    </td>
                    <td>
                        <div class="input-group">
                            <span class="input-group-text">VNĐ</span>
                            <input type="text" class="form-control" id="amount" name="amount[]" required>
                        </div>
                    </td>
                    <td>
                        <input type="text" class="form-control" id="person" name="person[]">
                    </td>
                    <td>
                        <textarea class="form-control" name="note[]" rows="1"></textarea>
                    </td>
                    <td>
                        <button class="btn btn-danger" onclick="removeInputRow(this)"> Xóa </button>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary float-end">Tạo</button>
            <a href="/expenses" class="btn btn-danger float-end mx-2">Quay lại</a>
        </div>
    </form>
</div>

<script>
    let tableInputRowHtml = ``;
    $(document).ready(function() {
        tableInputRowHtml = $('.table-form').find('tbody').html();

        $('.date-picker').datepicker({
            format: 'dd-mm-yyyy',
            autoclose:true
        });
    });

    $(document).keypress(event => {
        if (event.which == '13') {
            event.preventDefault();
        }
    });

    function addInputRow(elm) {
        let value = $(elm).val();
        const tbodyElm = $(elm).closest('tbody');
        const trElm = $(elm).closest('tr');

        const datePicked = trElm.find('.date-picker').val();

        if (value) {
            if ($('.reason').last().val() !== '') {
                tbodyElm.append(tableInputRowHtml);
                const datePicker = tbodyElm.find('.date-picker');
                datePicker.val();
                datePicker.datepicker({
                    format: 'dd-mm-yyyy',
                    autoclose:true
                });
                datePicker.val(datePicked);
            }
        }
    }

    function removeInputRow(elm) {
        $(elm).closest('tr').remove();
    }
</script>