<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<div class="row mt-5">
    <h1> Chỉnh sửa chi ngày <?= $this->date ?></h1>
    <form method="post" action="/expenses/do-edit">
        <div class="container">
            <table class="table table-striped table-form mt-3">
                <thead>
                <tr>
                    <th style="width: 150px">Ngày</th>
                    <th>Lý do chi</th>
                    <th style="width: 150px">Số tiền</th>
                    <th style="width: 150px">Người chi</th>
                    <th style="width: 400px">Ghi chú</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($this->expensesList as $expensesId => $expensesData):
                    $date = $expensesData['date'] ?? '';
                    $reason = $expensesData['reason'] ?? '-';
                    $amount = $expensesData['amount'] ?? 0;
                    $person = $expensesData['person'] ?? '-';
                    $note = $expensesData['note'] ?? '';
                ?>
                <tr>
                    <div>
                        <input type="hidden" name="expensesId[]" value="<?= $expensesId ?>">
                    </div>
                    <td>
                        <input class="form-control date-picker w-100" name="date[]" value="<?= $date ?>" autocomplete="off" required/>
                    </td>
                    <td>
                        <input type="text" class="form-control reason" id="reason" name="reason[]" required onchange="addInputRow(this)" value="<?= $reason ?>">
                    </td>
                    <td>
                        <div class="input-group">
                            <span class="input-group-text">VNĐ</span>
                            <input type="text" class="form-control" id="amount" name="amount[]" required value="<?= $amount ?>">
                        </div>
                    </td>
                    <td>
                        <input type="text" class="form-control" id="person" name="person[]" value="<?= $person ?>">
                    </td>
                    <td>
                        <textarea class="form-control" name="note[]" rows="1"><?= $note ?></textarea>
                    </td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary float-end">Lưu</button>
            <a href="/expenses" class="btn btn-danger float-end mx-2">Quay lại</a>
        </div>
    </form>
</div>

<script>
    let tableInputRowHtml = ``;
    $(document).ready(function() {
        tableInputRowHtml = $('.table-form').find('tbody').html();

        $('.date-picker').datepicker({
            format: 'dd/mm/yyyy',
            autoclose:true
        });
    });

    $(document).keypress(event => {
        if (event.which == '13') {
            event.preventDefault();
        }
    });
</script>