<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="container mt-4">
    <h1 class="mb-3"> Quản lý chi</h1>

    <div class="my-2">
        <div class="d-flex flex-wrap gap-2">
            <a href="/expenses/add" class="btn btn-primary">+ Thêm mới</a>
            <div class="input-group w-auto">
                <button class="btn btn-outline-primary" onclick="editByDate()">✏ Chỉnh sửa theo ngày</button>
                <input class="form-control date-picker" id="editDate" name="date" autocomplete="off" placeholder="dd-mm-yyyy" style="width:140px"/>
            </div>
        </div>
    </div>
    <table id="dataTable" class="table table-striped" style="width:100%">
        <thead>
        <tr>
            <th>STT</th>
            <th>Ngày</th>
            <th>Loại chi</th>
            <th>Lý do chi</th>
            <th>Số tiền</th>
            <th>Người chi</th>
            <th>Ghi chú</th>
            <th>Thao tác</th>
        </tr>
        </thead>
    </table>
</div>
<script>
    const table = initDataTable('#dataTable', {
        ...DATA_TABLES_CONFIG,
        ajax: {
            url: 'expenses/data-table-server-side',
            type: 'POST'
        },
        columns: [
            { name: 'no', data: 'no' },
            { name: 'date', data: 'date' },
            { name: 'typeText', data: 'typeText' },
            { name: 'reason', data: 'reason' },
            { name: 'amount', data: 'amount', render: $.fn.dataTable.render.number( ',') },
            { name: 'person', data: 'person' },
            { name: 'note', data: 'note' },
            {
                name: 'action', data: 'id',
                render: (id) =>
                    `<button class="btn btn-danger btn-sm" onclick="removeRow('expenses','${id}',table)">Xóa</button>`
            }
        ],
        serverSide: true
    });

    function remove(id) { removeRow('expenses', id, table); }

    function editByDate() {
        const date = $('#editDate').val();
        if (!date) {
            alert("Hãy nhập ngày chỉnh sửa !");
            return;
        }
        location.href = `/expenses/edit/${date}`;
    }
</script>